apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-vol
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-vol-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sql-serv
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: sql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: sql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-content
        image: mysql_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath : "/var/lib/mysql"
          name: sql-vol
      volumes:
      - name: sql-vol
        persistentVolumeClaim:
          claimName: sql-vol-claim